spring.application.name=demo

spring.datasource.url=jdbc:mysql://localhost:3306/crud-springboot
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=ma_cle_secrete_tres_longue_32chars_minimum
app.expiration-time=86400000